import type { Metadata } from "next";
import { Inter } from "next/font/google";  // Import Inter font from Google
import "../styles/globals.css";  // Import global styles

// Load the Inter font with a variable for custom font usage
const inter = Inter({
  variable: "--font-inter",  // Create a CSS variable for the font
  subsets: ["latin"],        // Only load the Latin subset
});

export const metadata: Metadata = {
  title: "Create Next App",       // Page title
  description: "Generated by create next app", // Page description
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">  {/* Set the language to English */}
      <body className={`${inter.variable} antialiased`}>  {/* Apply Inter font and antialiased style */}
        {children}  {/* Render child components here */}
      </body>
    </html>
  );
}
